---
- name: install aria2 packages
  apt: 
    name: ['aria2', 'git']
    state: present
    update_cache: yes

- name: Copy aria service and configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/systemd/system/aria2.service.j2", dest: "/etc/systemd/system/aria2.service", mode: "0644" }
    - { src: "etc/aria2.conf.j2", dest: "/etc/aria2.conf", mode: "0644" }
  notify:
    - restart aria2

- name: enable aria server
  systemd: 
    name: aria2
    enabled: yes
    state: started
    daemon_reload: yes

- name: checkout aria2-webui
  git:
    repo: 'https://github.com/ziahamza/webui-aria2.git'
    dest: /var/www/html/aria2