---
- name: install packages
  apt: 
    name: ['nfs-kernel-server', 'nfs-common', 'rpcbind', 'rsync']
    state: present
    update_cache: yes

- name: Create nfs group
  group:
    name: nfs
    gid: 5000
    state: present

- name: Create nfs user
  user:
    name: nfs
    shell: /bin/false
    state: present
    groups: nfs
    uid: 5000

- name: Creates directory
  file:
    path: /shared
    owner: nfs
    group: nfs
    mode: 2775
    recurse: yes
    state: directory

- name: comment out udp ipv6
  lineinfile:
    name: /etc/netconfig
    regexp: '^udp6'
    line: '#'

- name: comment out tcp ipv6
  lineinfile:
    name: /etc/netconfig
    regexp: '^tcp6'
    line: '#'

- name: copy needed configuration
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
    mode: "{{ item.mode }}"
  with_items:
    - { source: "etc/exports.j2", destination: "/etc/exports", mode: "0650" }
  notify:
    - restart exports

- name: enable nfs server
  service: name={{ item }} enabled=yes state=started
  with_items:
  - rpcbind
  - rpc-statd
  - nfs-kernel-server
